"""
Database Management Module
==========================
Handles SQLite database lifecycle, connection pooling, schema migrations, and indexing.

Database Schema Overview:
  1. `users`: Web console authentication and role-based access control (RBAC).
  2. `devices`: Physical/virtual network assets discovered via ARP/ICMP or registered sensors.
  3. `topology_edges`: Directed network connectivity graph edges used by CyberTwin simulations.
  4. `cyberdna_baselines`: Running statistical metrics (mean, variance, sample count) per entity.
  5. `events`: High-throughput normalized telemetry log records from monitored endpoints.
  6. `alerts`: Security anomaly detections with MITRE ATT&CK techniques and evidence graphs.
  7. `simulations`: Lateral movement blast-radius propagation runs generated by CyberTwin.
  8. `processed_batches`: Deduplication registry for sensor batch ingestion.
"""
import sqlite3
import os
from pathlib import Path
from contextlib import contextmanager
from datetime import datetime, timezone
from werkzeug.security import generate_password_hash

# Default fallback SQLite path if none is explicitly specified in config
DEFAULT_DB_PATH = os.path.join(os.path.dirname(__file__), "sentineltwin.db")


def _ensure_db_dir(path: str):
    """Safely ensures the parent directory of a SQLite database file exists."""
    if not path or path == ":memory:" or path.startswith("file:"):
        return
    db_file = Path(path)
    if db_file.parent:
        db_file.parent.mkdir(parents=True, exist_ok=True)


@contextmanager
def get_conn(db_path=None):
    """
    Thread-safe connection context manager for SQLite transactions.

    Yields a sqlite3.Connection with Row factory enabled (dict-like column access).
    Automatically issues COMMIT on normal exit or ROLLBACK if an unhandled exception occurs.
    Guarantees connection closure in the finally block.

    Args:
        db_path (str, optional): Absolute or relative filesystem path to the SQLite file.
    """
    path = db_path or DEFAULT_DB_PATH
    _ensure_db_dir(path)
    conn = sqlite3.connect(path)
    # Enable sqlite3.Row so query results can be accessed by column name (row['device_id'])
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()  # Persist changes on clean block exit
    except Exception:
        conn.rollback()  # Rollback transaction on failure to ensure atomic consistency
        raise
    finally:
        conn.close()  # Cleanly release filesystem lock


def init_db(db_path=None):
    """
    Initializes database tables, creates performance indexes, seeds optional admin user,
    and applies non-destructive column migrations for backwards compatibility.
    """
    path = db_path or DEFAULT_DB_PATH
    _ensure_db_dir(path)
    with get_conn(path) as conn:
        cur = conn.cursor()

        # -----------------------------------------------------------------
        # 1. Users Table: Web dashboard credentials and RBAC roles
        # -----------------------------------------------------------------
        cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('Administrator', 'Sensor', 'Viewer')),
                created_at TEXT NOT NULL
            )
        """)

        # 2. Devices Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS devices (
                id TEXT PRIMARY KEY,
                ip_address TEXT UNIQUE,
                mac_address TEXT,
                hostname TEXT,
                vendor TEXT,
                device_type TEXT,
                os TEXT,
                status TEXT DEFAULT 'Online',
                first_seen TEXT,
                last_seen TEXT,
                sensor_connected INTEGER DEFAULT 0,
                trust_level TEXT DEFAULT 'Adaptive',
                discovery_method TEXT,
                criticality INTEGER DEFAULT 1,
                risk_score REAL DEFAULT 0.0,
                risk_level TEXT DEFAULT 'ADAPTIVE',
                auth_status TEXT DEFAULT 'AUTHORIZED',
                transport_mode TEXT DEFAULT 'DIRECT',
                sensor_token_hash TEXT,
                last_event_received TEXT
            )
        """)

        # 3. Topology Edges Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS topology_edges (
                source TEXT NOT NULL,
                target TEXT NOT NULL,
                relationship_type TEXT DEFAULT 'network_reachability',
                observed INTEGER DEFAULT 1,
                inferred INTEGER DEFAULT 0,
                confidence REAL DEFAULT 0.85,
                protocol TEXT DEFAULT 'IP',
                port INTEGER,
                evidence TEXT,
                PRIMARY KEY (source, target),
                FOREIGN KEY (source) REFERENCES devices(id) ON DELETE CASCADE,
                FOREIGN KEY (target) REFERENCES devices(id) ON DELETE CASCADE
            )
        """)

        # 4. CyberDNA Baselines Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS cyberdna_baselines (
                metric_key TEXT NOT NULL,
                entity_id TEXT NOT NULL,
                sample_count INTEGER DEFAULT 0,
                mean REAL DEFAULT 0.0,
                m2 REAL DEFAULT 0.0,
                variance REAL DEFAULT 0.0,
                standard_deviation REAL DEFAULT 0.0,
                last_updated TEXT NOT NULL,
                peer_group TEXT DEFAULT 'default',
                short_term_mean REAL DEFAULT 0.0,
                PRIMARY KEY (metric_key, entity_id)
            )
        """)

        # 5. Events Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                device_id TEXT NOT NULL,
                channel TEXT NOT NULL DEFAULT 'Security',
                event_id INTEGER NOT NULL DEFAULT 0,
                record_id INTEGER NOT NULL DEFAULT 0,
                event_timestamp TEXT NOT NULL,
                ingested_at TEXT NOT NULL,
                user TEXT,
                process_name TEXT,
                parent_process TEXT,
                command_line TEXT,
                source_ip TEXT,
                destination_ip TEXT,
                destination_port INTEGER,
                logon_type TEXT,
                risk_score REAL DEFAULT 0.0,
                details TEXT,
                metadata TEXT,
                event_type TEXT,
                source TEXT DEFAULT 'Sysmon',
                status TEXT,
                FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
            )
        """)

        # 6. Alerts Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS alerts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                device_id TEXT NOT NULL,
                severity TEXT NOT NULL,
                category TEXT DEFAULT 'Threat Detected',
                title TEXT DEFAULT '',
                description TEXT NOT NULL,
                timestamp TEXT,
                status TEXT DEFAULT 'Open',
                risk_points INTEGER DEFAULT 0,
                created_at TEXT,
                mitre_technique_id TEXT DEFAULT '',
                mitre_technique_name TEXT DEFAULT '',
                mitre_tactic TEXT DEFAULT '',
                evidence_graph TEXT DEFAULT '{}',
                FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
            )
        """)

        # 7. Simulations Table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS simulations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                incident_id INTEGER DEFAULT 0,
                source_device TEXT NOT NULL,
                target_devices TEXT DEFAULT '[]',
                path TEXT DEFAULT '[]',
                hop_count INTEGER DEFAULT 0,
                critical_assets TEXT DEFAULT '[]',
                estimated_impact TEXT DEFAULT 'LOW',
                created_at TEXT NOT NULL
            )
        """)

        # 8. Processed Batches Table (Duplicate-safe batch tracking)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS processed_batches (
                batch_id TEXT PRIMARY KEY,
                device_id TEXT NOT NULL,
                processed_at TEXT NOT NULL,
                event_count INTEGER NOT NULL DEFAULT 0,
                transport TEXT DEFAULT 'DIRECT'
            )
        """)

        # 9. Safe Schema Migrations for existing databases
        cur.execute("PRAGMA table_info(events)")
        existing_event_cols = [row["name"] for row in cur.fetchall()]
        if "channel" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN channel TEXT NOT NULL DEFAULT 'Security'")
        if "event_id" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN event_id INTEGER NOT NULL DEFAULT 0")
        if "record_id" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN record_id INTEGER NOT NULL DEFAULT 0")
        if "event_timestamp" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN event_timestamp TEXT")
            if "timestamp" in existing_event_cols:
                cur.execute("UPDATE events SET event_timestamp = timestamp WHERE event_timestamp IS NULL")
            else:
                now_str = datetime.now(timezone.utc).isoformat()
                cur.execute("UPDATE events SET event_timestamp = ? WHERE event_timestamp IS NULL", (now_str,))
        if "ingested_at" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN ingested_at TEXT")
        if "user" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN user TEXT")
        if "process_name" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN process_name TEXT")
        if "parent_process" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN parent_process TEXT")
        if "command_line" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN command_line TEXT")
        if "source_ip" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN source_ip TEXT")
        if "destination_ip" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN destination_ip TEXT")
        if "destination_port" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN destination_port INTEGER")
        if "logon_type" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN logon_type TEXT")
        if "metadata" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN metadata TEXT")
        if "status" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN status TEXT")
        if "details" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN details TEXT")
        if "event_type" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN event_type TEXT")
        if "source" not in existing_event_cols:
            cur.execute("ALTER TABLE events ADD COLUMN source TEXT DEFAULT 'Sysmon'")

        cur.execute("PRAGMA table_info(alerts)")
        existing_alert_cols = [row["name"] for row in cur.fetchall()]
        if "mitre_technique_id" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN mitre_technique_id TEXT DEFAULT ''")
        if "mitre_technique_name" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN mitre_technique_name TEXT DEFAULT ''")
        if "mitre_tactic" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN mitre_tactic TEXT DEFAULT ''")
        if "evidence_graph" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN evidence_graph TEXT DEFAULT '{}'")
        if "title" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN title TEXT DEFAULT ''")
        if "risk_points" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN risk_points INTEGER DEFAULT 0")
        if "created_at" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN created_at TEXT")
            cur.execute("UPDATE alerts SET created_at = timestamp WHERE created_at IS NULL")
        if "category" not in existing_alert_cols:
            cur.execute("ALTER TABLE alerts ADD COLUMN category TEXT DEFAULT 'Threat Detected'")

        cur.execute("PRAGMA table_info(devices)")
        existing_device_cols = [row["name"] for row in cur.fetchall()]
        if "sensor_connected" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN sensor_connected INTEGER DEFAULT 0")
        if "trust_level" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN trust_level TEXT DEFAULT 'Adaptive'")
        if "discovery_method" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN discovery_method TEXT")
        if "risk_score" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN risk_score REAL DEFAULT 0.0")
        if "risk_level" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN risk_level TEXT DEFAULT 'ADAPTIVE'")
        if "auth_status" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN auth_status TEXT DEFAULT 'AUTHORIZED'")
        if "transport_mode" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN transport_mode TEXT DEFAULT 'DIRECT'")
        if "sensor_token_hash" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN sensor_token_hash TEXT")
        if "last_event_received" not in existing_device_cols:
            cur.execute("ALTER TABLE devices ADD COLUMN last_event_received TEXT")

        cur.execute("PRAGMA table_info(cyberdna_baselines)")
        existing_baseline_cols = [row["name"] for row in cur.fetchall()]
        if "peer_group" not in existing_baseline_cols:
            cur.execute("ALTER TABLE cyberdna_baselines ADD COLUMN peer_group TEXT DEFAULT 'default'")
        if "short_term_mean" not in existing_baseline_cols:
            cur.execute("ALTER TABLE cyberdna_baselines ADD COLUMN short_term_mean REAL DEFAULT 0.0")

        # 10. Indexes
        cur.execute("CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(event_timestamp)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_events_device_id ON events(device_id)")
        cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_events_device_channel_record ON events(device_id, channel, record_id) WHERE record_id IS NOT NULL AND record_id > 0")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(severity, status)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_devices_criticality ON devices(criticality)")

        # 10. Bootstrap Initial Administrator (Opt-in via environment variables only)
        bootstrap_user = os.getenv("BOOTSTRAP_ADMIN_USER", "").strip()
        bootstrap_password = os.getenv("BOOTSTRAP_ADMIN_PASSWORD", "").strip()
        if bootstrap_user and bootstrap_password:
            cur.execute("SELECT COUNT(*) as count FROM users WHERE username = ?", (bootstrap_user,))
            if cur.fetchone()["count"] == 0:
                now = datetime.now(timezone.utc).isoformat()
                cur.execute("""
                    INSERT INTO users (username, password_hash, role, created_at)
                    VALUES (?, ?, ?, ?)
                """, (bootstrap_user, generate_password_hash(bootstrap_password), "Administrator", now))
